########################################################################################
### HYPRLAND VARIABLES
########################################################################################

# Created by mugiwara@loki.local on Sun Feb 01 2026

# This file contains variables for the Hyprland configuration.

$mainMod = SUPER # Sets "Windows" key as main modifier

#################
### MONITORS ###
#################

$monitor1 = DP-3
$monitor2 = HDMI-A-2

#################
### PROGRAMS ###
#################

$terminal = kitty
$fileManager = thunar
$browser = google-chrome-stable
$menu = rofi -show drun
$picker = hyprpicker -al
$lock = hyprlock
$editor = cursor
$screenshot = grim -g "$(slurp)" - | wl-copy

########################
### CACHE VARIABLES ####
########################

$wallpaperCache = ~/.cache/appearance/wallpaper.png
$pfpCache = ~/.cache/appearance/pfp.jpg

########################
### SCRIPT VARIABLES ###
########################

$wallpaperScript = ~/.local/bin/select_wallpaper.sh
$toggleRofiScript = ~/.local/bin/toggle_rofi.sh
$songDetailScript = ~/.local/bin/song_detail.sh
$reloadScript = ~/.local/bin/reload_all_services.sh
$themeMenuScript = ~/.local/bin/theme-menu.sh
