########################################################################################
### HYPRLAND AUTOSTART
########################################################################################

# Created by mugiwara@loki.local on Sun Feb 01 2026

# This file contains autostart scripts for the Hyprland configuration.

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

########################
## PROGRAMS AUTOSTART ##
########################

exec-once = systemctl --user start hyprpolkitagent
exec-once = /usr/lib/xdg-desktop-portal
exec-once = usr/lib/xdg-desktop-portal-hyprland
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = hyprpaper
exec-once = hyprsunset
exec-once = nm-applet
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = openrgb --gui --startminimized

########################
## SCRIPT AUTOSTART ##
########################

exec-once = $wallpaperScript
