########################################################################################
### HYPRLAND WORKSPACES
########################################################################################

# Created by mugiwara@loki.local on Sun Feb 01 2026

# This file contains workspaces for the Hyprland configuration.

workspace = 1, monitor:$monitor1
workspace = 2, monitor:$monitor2, layout:scrolling
workspace = 3, monitor:$monitor2
workspace = 4, monitor:$monitor2
workspace = 5, monitor:$monitor2
workspace = 6, monitor:$monitor1
workspace = 7, monitor:$monitor2
workspace = 8, monitor:$monitor1
workspace = 9, monitor:$monitor2, layout:scrolling
workspace = 10, monitor:$monitor2, layout:scrolling

scrolling {
	column_width = 0.9
	direction = down
	focus_fit_method = 0
	follow_focus = true
	follow_min_visible = 0.4
	fullscreen_on_one_column = true
}
